[pytest]
filterwarnings =
    ignore:pkg_resources is deprecated as an API:UserWarning:gym_sokoban
    ignore:Starting with ImageIO v3:DeprecationWarning:gym_sokoban
    ignore:'mode' parameter is deprecated:DeprecationWarning:vagen.envs.sokoban.utils.utils
